<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'All notifications have been deleted.' => 'Все уведомления удалены.',
    'All notifications have been marked as read.' => 'Все уведомления отмечены как прочитанные.',
    'Delete all' => 'Удалить все',
    'Mark all as read' => 'Прочитать все',
    'Mark as read' => 'Отметить как прочитанное',
    'Notifications' => 'Уведомления',
    'Read' => 'Прочитать',
    'There are no notifications to show' => 'Нет уведомлений',
    'View all' => 'Просмотреть все',
    'a moment' => 'момент',
    'ago' => 'назад',
    '{n, plural, one{one day} other{# days}}' => '{n, plural, one{день} other{# дней}}',
    '{n, plural, one{one hour} other{# hours}}' => '{n, plural, one{час} other{# часов}}',
    '{n, plural, one{one minute} other{# minutes}}' => '{n, plural, one{минуту} other{# минут}}',
    '{n, plural, one{one month} other{# months}}' => '{n, plural, one{месяц} other{# месяцев}}',
    '{n, plural, one{one second} other{# seconds}}' => '{n, plural, one{секунду} other{# секунд}}',
    '{n, plural, one{one week} other{# weeks}}' => '{n, plural, one{неделю} other{# недель}}',
    '{n, plural, one{one year} other{# years}}' => '{n, plural, one{год} other{# года}}',
];
